window.FLUXFRAME_SITE = {
  "brand": "fluxframe.",
  "mark": "assets/portfolio/26-fluxframe-mark.png",
  "background": "assets/portfolio/45-fluxframe-wordmark.png",
  "texture": "assets/portfolio/36-fluxframe-texture.png",
  "concept": "assets/concepts/fluxframe-generated-concept.png",
  "linkedin": "https://www.linkedin.com/in/imivani/",
  "websitesToAdd": [
    {
      "title": "Future Website Case Study",
      "status": "Ready for link",
      "url": "#",
      "note": "Reserved for live site links, launch notes, and selected screenshots."
    }
  ]
};

window.FLUXFRAME_ITEMS = [
  {
    "id": "instagram-milestone",
    "title": "Instagram Milestone",
    "kind": "NFT Campaign",
    "category": "nft",
    "description": "Color-blocked HypeBears social milestone artwork.",
    "src": "assets/portfolio/01-instagram-milestone.jpg",
    "width": 1280,
    "height": 1280,
    "orientation": "square",
    "animated": false,
    "featured": false,
    "hero": true,
    "webCase": false,
    "year": "2022"
  },
  {
    "id": "motion-study-01",
    "title": "Animated Signature 01",
    "kind": "Animated Signature",
    "category": "motion",
    "description": "Animated signature banner.",
    "src": "assets/portfolio/02-motion-study-01.gif",
    "width": 400,
    "height": 160,
    "orientation": "banner",
    "animated": true,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "expanded-discord",
    "title": "Expanded Discord",
    "kind": "Community Campaign",
    "category": "thread",
    "description": "Purple HypeBears Discord expansion banner.",
    "src": "assets/portfolio/03-expanded-discord.png",
    "width": 976,
    "height": 488,
    "orientation": "wide",
    "animated": false,
    "featured": true,
    "hero": true,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "anonymous-hosting-page",
    "title": "CrazyRDP",
    "kind": "Web Design",
    "category": "web",
    "description": "Real anonymous hosting landing page for CrazyRDP.",
    "src": "assets/portfolio/04-anonymous-hosting-page.png",
    "width": 1200,
    "height": 3704,
    "orientation": "tall",
    "animated": false,
    "featured": false,
    "hero": false,
    "webCase": true,
    "year": "2023"
  },
  {
    "id": "motion-study-02",
    "title": "Animated Signature 02",
    "kind": "Animated Signature",
    "category": "motion",
    "description": "Animated signature banner.",
    "src": "assets/portfolio/05-motion-study-02.gif",
    "width": 1200,
    "height": 526,
    "orientation": "banner",
    "animated": true,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "motion-study-03",
    "title": "Animated Signature 03",
    "kind": "Animated Signature",
    "category": "motion",
    "description": "Animated signature banner.",
    "src": "assets/portfolio/06-motion-study-03.gif",
    "width": 1200,
    "height": 499,
    "orientation": "banner",
    "animated": true,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "upvotic-landing",
    "title": "iPredict",
    "kind": "Web Design",
    "category": "web",
    "description": "A smarter way to trade cryptocurrency landing page.",
    "src": "assets/portfolio/07-upvotic-landing.png",
    "width": 1200,
    "height": 2591,
    "orientation": "tall",
    "animated": false,
    "featured": false,
    "hero": false,
    "webCase": true,
    "year": "2023"
  },
  {
    "id": "wrap-mechanics",
    "title": "Wrap Mechanics",
    "kind": "NFT Explainer",
    "category": "nft",
    "description": "HypeBears wrap process explainer.",
    "src": "assets/portfolio/08-wrap-mechanics.png",
    "width": 1280,
    "height": 718,
    "orientation": "wide",
    "animated": false,
    "featured": true,
    "hero": true,
    "webCase": false,
    "year": "2022"
  },
  {
    "id": "motion-study-04",
    "title": "Animated Signature 04",
    "kind": "Animated Signature",
    "category": "motion",
    "description": "Animated signature banner.",
    "src": "assets/portfolio/09-motion-study-04.gif",
    "width": 400,
    "height": 160,
    "orientation": "banner",
    "animated": true,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "motion-study-05",
    "title": "Animated Signature 05",
    "kind": "Animated Signature",
    "category": "motion",
    "description": "Animated signature banner.",
    "src": "assets/portfolio/10-motion-study-05.gif",
    "width": 400,
    "height": 160,
    "orientation": "banner",
    "animated": true,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "hype-bears-cover",
    "title": "Hype Bears",
    "kind": "Startup Project / NFT Launch",
    "category": "crypto",
    "description": "Dark Hype Bears identity artwork.",
    "src": "assets/portfolio/11-hype-bears-cover.png",
    "width": 795,
    "height": 621,
    "orientation": "wide",
    "animated": false,
    "featured": true,
    "hero": true,
    "webCase": false,
    "year": "2022"
  },
  {
    "id": "recent-projects-cover",
    "title": "Recent Projects Cover",
    "kind": "Brand System",
    "category": "brand",
    "description": "Fluxframe recent projects cover tile.",
    "src": "assets/portfolio/12-recent-projects-cover.png",
    "width": 795,
    "height": 621,
    "orientation": "wide",
    "animated": false,
    "featured": true,
    "hero": true,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "motion-study-06",
    "title": "Animated Signature 06",
    "kind": "Animated Signature",
    "category": "motion",
    "description": "Animated signature banner.",
    "src": "assets/portfolio/13-motion-study-06.gif",
    "width": 600,
    "height": 240,
    "orientation": "banner",
    "animated": true,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "collectible-bears",
    "title": "Collectible Bears",
    "kind": "NFT Campaign",
    "category": "nft",
    "description": "HypeBears collectible launch banner.",
    "src": "assets/portfolio/14-collectible-bears.png",
    "width": 1280,
    "height": 718,
    "orientation": "wide",
    "animated": false,
    "featured": true,
    "hero": true,
    "webCase": false,
    "year": "2022"
  },
  {
    "id": "b4u-army-landing",
    "title": "B4U Army Landing",
    "kind": "Web Design",
    "category": "web",
    "description": "Dark game/community landing page screenshot.",
    "src": "assets/portfolio/15-b4u-army-landing.png",
    "width": 1200,
    "height": 2697,
    "orientation": "tall",
    "animated": false,
    "featured": false,
    "hero": false,
    "webCase": true,
    "year": "2023"
  },
  {
    "id": "motion-study-07",
    "title": "Animated Signature 07",
    "kind": "Animated Signature",
    "category": "motion",
    "description": "Animated signature banner.",
    "src": "assets/portfolio/16-motion-study-07.gif",
    "width": 400,
    "height": 160,
    "orientation": "banner",
    "animated": true,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "motion-study-08",
    "title": "Animated Signature 08",
    "kind": "Animated Signature",
    "category": "motion",
    "description": "Animated signature banner.",
    "src": "assets/portfolio/17-motion-study-08.gif",
    "width": 400,
    "height": 160,
    "orientation": "banner",
    "animated": true,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "twenty-four-hours",
    "title": "Twenty-Four Hours",
    "kind": "NFT Campaign",
    "category": "nft",
    "description": "Pale HypeBears launch countdown banner.",
    "src": "assets/portfolio/18-twenty-four-hours.png",
    "width": 976,
    "height": 488,
    "orientation": "wide",
    "animated": false,
    "featured": false,
    "hero": true,
    "webCase": false,
    "year": "2022"
  },
  {
    "id": "motion-study-09",
    "title": "Animated Signature 09",
    "kind": "Animated Signature",
    "category": "motion",
    "description": "Animated signature banner.",
    "src": "assets/portfolio/19-motion-study-09.gif",
    "width": 400,
    "height": 160,
    "orientation": "banner",
    "animated": true,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "motion-study-10",
    "title": "Animated Signature 10",
    "kind": "Animated Signature",
    "category": "motion",
    "description": "Animated signature banner.",
    "src": "assets/portfolio/20-motion-study-10.gif",
    "width": 400,
    "height": 160,
    "orientation": "banner",
    "animated": true,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "casetify-collaboration",
    "title": "Casetify Collaboration",
    "kind": "NFT Campaign",
    "category": "nft",
    "description": "HypeBears collaboration announcement graphic.",
    "src": "assets/portfolio/21-casetify-collaboration.png",
    "width": 976,
    "height": 488,
    "orientation": "wide",
    "animated": false,
    "featured": true,
    "hero": true,
    "webCase": false,
    "year": "2022"
  },
  {
    "id": "motion-study-11",
    "title": "Animated Signature 11",
    "kind": "Animated Signature",
    "category": "motion",
    "description": "Animated signature banner.",
    "src": "assets/portfolio/22-motion-study-11.gif",
    "width": 400,
    "height": 160,
    "orientation": "banner",
    "animated": true,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "crypto-bot-page",
    "title": "Crypto Bot Page",
    "kind": "Web Design",
    "category": "web",
    "description": "Cold-blooded crypto bot landing page design.",
    "src": "assets/portfolio/23-crypto-bot-page.png",
    "width": 1200,
    "height": 2835,
    "orientation": "tall",
    "animated": false,
    "featured": true,
    "hero": false,
    "webCase": true,
    "year": "2023"
  },
  {
    "id": "motion-study-12",
    "title": "Animated Signature 12",
    "kind": "Animated Signature",
    "category": "motion",
    "description": "Animated signature banner.",
    "src": "assets/portfolio/24-motion-study-12.gif",
    "width": 600,
    "height": 240,
    "orientation": "banner",
    "animated": true,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "micro-motion-01",
    "title": "Animated Signature Detail",
    "kind": "Animated Signature",
    "category": "motion",
    "description": "Compact animated banner.",
    "src": "assets/portfolio/25-micro-motion-01.gif",
    "width": 600,
    "height": 150,
    "orientation": "banner",
    "animated": true,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "fluxframe-mark",
    "title": "Fluxframe Mark",
    "kind": "Brand Asset",
    "category": "brand",
    "description": "Fluxframe ff monogram asset.",
    "src": "assets/portfolio/26-fluxframe-mark.png",
    "width": 242,
    "height": 242,
    "orientation": "square",
    "animated": false,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "motion-study-13",
    "title": "Animated Signature 13",
    "kind": "Animated Signature",
    "category": "motion",
    "description": "Animated signature banner.",
    "src": "assets/portfolio/27-motion-study-13.gif",
    "width": 600,
    "height": 240,
    "orientation": "banner",
    "animated": true,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "website-launched",
    "title": "Website Launched",
    "kind": "NFT Campaign",
    "category": "nft",
    "description": "Yellow HypeBears website launch banner.",
    "src": "assets/portfolio/28-website-launched.jpg",
    "width": 976,
    "height": 488,
    "orientation": "wide",
    "animated": false,
    "featured": true,
    "hero": true,
    "webCase": false,
    "year": "2022"
  },
  {
    "id": "motion-study-14",
    "title": "Animated Signature 14",
    "kind": "Animated Signature",
    "category": "motion",
    "description": "Animated signature banner.",
    "src": "assets/portfolio/29-motion-study-14.gif",
    "width": 400,
    "height": 160,
    "orientation": "banner",
    "animated": true,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "motion-study-15",
    "title": "Animated Signature 15",
    "kind": "Animated Signature",
    "category": "motion",
    "description": "Animated signature banner.",
    "src": "assets/portfolio/30-motion-study-15.gif",
    "width": 400,
    "height": 160,
    "orientation": "banner",
    "animated": true,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "xummtools-landing",
    "title": "XummTools Landing",
    "kind": "Web Design",
    "category": "web",
    "description": "Tall mobile-first crypto tools page.",
    "src": "assets/portfolio/31-xummtools-landing.jpg",
    "width": 505,
    "height": 2048,
    "orientation": "tall",
    "animated": false,
    "featured": false,
    "hero": false,
    "webCase": true,
    "year": "2023"
  },
  {
    "id": "fluxframe-contour-cover",
    "title": "Fluxframe Contour Cover",
    "kind": "Brand System",
    "category": "brand",
    "description": "Fluxframe dark contour portfolio cover.",
    "src": "assets/portfolio/32-fluxframe-contour-cover.png",
    "width": 1078,
    "height": 611,
    "orientation": "wide",
    "animated": false,
    "featured": true,
    "hero": true,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "motion-study-16",
    "title": "Animated Signature 16",
    "kind": "Animated Signature",
    "category": "motion",
    "description": "Animated signature banner.",
    "src": "assets/portfolio/33-motion-study-16.gif",
    "width": 600,
    "height": 240,
    "orientation": "banner",
    "animated": true,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "motion-study-17",
    "title": "Animated Signature 17",
    "kind": "Animated Signature",
    "category": "motion",
    "description": "Animated signature banner.",
    "src": "assets/portfolio/34-motion-study-17.gif",
    "width": 600,
    "height": 240,
    "orientation": "banner",
    "animated": true,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "evl-project-page",
    "title": "EVL Project Page",
    "kind": "Web Design",
    "category": "web",
    "description": "Long dark EVL project landing page.",
    "src": "assets/portfolio/35-evl-project-page.jpg",
    "width": 1200,
    "height": 5000,
    "orientation": "tall",
    "animated": false,
    "featured": true,
    "hero": false,
    "webCase": true,
    "year": "2023"
  },
  {
    "id": "fluxframe-texture",
    "title": "Fluxframe Texture",
    "kind": "Brand System",
    "category": "brand",
    "description": "Dark contour texture background asset.",
    "src": "assets/portfolio/36-fluxframe-texture.png",
    "width": 1078,
    "height": 611,
    "orientation": "wide",
    "animated": false,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "motion-study-18",
    "title": "Animated Signature 18",
    "kind": "Animated Signature",
    "category": "motion",
    "description": "Animated signature banner.",
    "src": "assets/portfolio/37-motion-study-18.gif",
    "width": 400,
    "height": 160,
    "orientation": "banner",
    "animated": true,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "motion-study-19",
    "title": "Animated Signature 19",
    "kind": "Animated Signature",
    "category": "motion",
    "description": "Animated signature banner.",
    "src": "assets/portfolio/38-motion-study-19.gif",
    "width": 400,
    "height": 160,
    "orientation": "banner",
    "animated": true,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "website-launch-alt",
    "title": "Website Launch Alt",
    "kind": "NFT Campaign",
    "category": "nft",
    "description": "Yellow HypeBears website launch variant.",
    "src": "assets/portfolio/39-website-launch-alt.jpg",
    "width": 976,
    "height": 488,
    "orientation": "wide",
    "animated": false,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "2022"
  },
  {
    "id": "motion-study-20",
    "title": "Animated Signature 20",
    "kind": "Animated Signature",
    "category": "motion",
    "description": "Animated signature banner.",
    "src": "assets/portfolio/40-motion-study-20.gif",
    "width": 400,
    "height": 160,
    "orientation": "banner",
    "animated": true,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "projectxl-landing",
    "title": "ProjectXL Landing",
    "kind": "Web Design",
    "category": "web",
    "description": "Tall blue-and-white project landing page.",
    "src": "assets/portfolio/41-projectxl-landing.png",
    "width": 1304,
    "height": 4687,
    "orientation": "tall",
    "animated": false,
    "featured": false,
    "hero": false,
    "webCase": true,
    "year": "2023"
  },
  {
    "id": "motion-study-21",
    "title": "Animated Signature 21",
    "kind": "Animated Signature",
    "category": "motion",
    "description": "Animated signature banner.",
    "src": "assets/portfolio/42-motion-study-21.gif",
    "width": 400,
    "height": 160,
    "orientation": "banner",
    "animated": true,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "200k-followers",
    "title": "200K Followers",
    "kind": "NFT Campaign",
    "category": "nft",
    "description": "Blue HypeBears follower milestone graphic.",
    "src": "assets/portfolio/43-200k-followers.jpg",
    "width": 1274,
    "height": 869,
    "orientation": "wide",
    "animated": false,
    "featured": true,
    "hero": true,
    "webCase": false,
    "year": "2022"
  },
  {
    "id": "particle-loop",
    "title": "Animated Signature Loop",
    "kind": "Animated Signature",
    "category": "motion",
    "description": "Abstract dotted motion texture.",
    "src": "assets/portfolio/44-particle-loop.gif",
    "width": 400,
    "height": 160,
    "orientation": "banner",
    "animated": true,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "fluxframe-wordmark",
    "title": "Fluxframe Wordmark",
    "kind": "Brand System",
    "category": "brand",
    "description": "Fluxframe wordmark on contour texture.",
    "src": "assets/portfolio/45-fluxframe-wordmark.png",
    "width": 1059,
    "height": 316,
    "orientation": "banner",
    "animated": false,
    "featured": true,
    "hero": true,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "launch-date",
    "title": "Launch Date",
    "kind": "NFT Campaign",
    "category": "nft",
    "description": "HypeBears launch date social artwork.",
    "src": "assets/portfolio/46-launch-date.jpg",
    "width": 1280,
    "height": 1280,
    "orientation": "square",
    "animated": false,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "2022"
  },
  {
    "id": "motion-study-22",
    "title": "Animated Signature 22",
    "kind": "Animated Signature",
    "category": "motion",
    "description": "Animated signature banner.",
    "src": "assets/portfolio/47-motion-study-22.gif",
    "width": 400,
    "height": 160,
    "orientation": "banner",
    "animated": true,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "motion-study-23",
    "title": "Animated Signature 23",
    "kind": "Animated Signature",
    "category": "motion",
    "description": "Animated compact banner.",
    "src": "assets/portfolio/48-motion-study-23.gif",
    "width": 380,
    "height": 152,
    "orientation": "banner",
    "animated": true,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "winners-announcement",
    "title": "Winners Announcement",
    "kind": "NFT Campaign",
    "category": "nft",
    "description": "HypeBears giveaway winners artwork.",
    "src": "assets/portfolio/49-winners-announcement.png",
    "width": 976,
    "height": 488,
    "orientation": "wide",
    "animated": false,
    "featured": true,
    "hero": true,
    "webCase": false,
    "year": "2022"
  },
  {
    "id": "securedvpn-landing",
    "title": "SecuredVPN Landing",
    "kind": "Web Design",
    "category": "web",
    "description": "Red VPN landing page design.",
    "src": "assets/portfolio/50-securedvpn-landing.png",
    "width": 1200,
    "height": 2564,
    "orientation": "tall",
    "animated": false,
    "featured": false,
    "hero": false,
    "webCase": true,
    "year": "2023"
  },
  {
    "id": "motion-study-24",
    "title": "Animated Signature 24",
    "kind": "Animated Signature",
    "category": "motion",
    "description": "Animated signature banner.",
    "src": "assets/portfolio/51-motion-study-24.gif",
    "width": 600,
    "height": 240,
    "orientation": "banner",
    "animated": true,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "motion-study-25",
    "title": "Animated Signature 25",
    "kind": "Animated Signature",
    "category": "motion",
    "description": "Animated signature banner.",
    "src": "assets/portfolio/52-motion-study-25.gif",
    "width": 400,
    "height": 160,
    "orientation": "banner",
    "animated": true,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "netflix-upgrades-page",
    "title": "Netflix Upgrades Page",
    "kind": "Web Design",
    "category": "web",
    "description": "Dark product upgrade landing page.",
    "src": "assets/portfolio/53-netflix-upgrades-page.png",
    "width": 1200,
    "height": 2365,
    "orientation": "tall",
    "animated": false,
    "featured": true,
    "hero": false,
    "webCase": true,
    "year": "2024"
  },
  {
    "id": "auction-house-page",
    "title": "Auction House Page",
    "kind": "Web Design",
    "category": "web",
    "description": "Orange auction house landing page.",
    "src": "assets/portfolio/54-auction-house-page.png",
    "width": 1200,
    "height": 2988,
    "orientation": "tall",
    "animated": false,
    "featured": true,
    "hero": false,
    "webCase": true,
    "year": "2024"
  },
  {
    "id": "gm-co-cover",
    "title": "GM.CO / PXN",
    "kind": "Startup Project",
    "category": "crypto",
    "description": "PXN and GM.CO project cover graphic.",
    "src": "assets/portfolio/55-gm-co-cover.png",
    "width": 795,
    "height": 621,
    "orientation": "wide",
    "animated": false,
    "featured": false,
    "hero": true,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "flavatools-partnership",
    "title": "FlavaTools Partnership",
    "kind": "Brand Campaign",
    "category": "brand",
    "description": "Blue FlavaTools and Azeroth partnership banner.",
    "src": "assets/portfolio/56-flavatools-partnership.jpg",
    "width": 1920,
    "height": 1080,
    "orientation": "wide",
    "animated": false,
    "featured": true,
    "hero": true,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "rdp-sh-landing",
    "title": "rdp.sh",
    "kind": "Web Design",
    "category": "web",
    "description": "Dark RDP product landing page.",
    "src": "assets/portfolio/57-rdp-sh-landing.jpg",
    "width": 1200,
    "height": 4200,
    "orientation": "tall",
    "animated": false,
    "featured": true,
    "hero": false,
    "webCase": true,
    "year": "2024"
  },
  {
    "id": "motion-study-26",
    "title": "Animated Signature 26",
    "kind": "Animated Signature",
    "category": "motion",
    "description": "Animated signature banner.",
    "src": "assets/portfolio/58-motion-study-26.gif",
    "width": 400,
    "height": 160,
    "orientation": "banner",
    "animated": true,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "motion-study-27",
    "title": "Animated Signature 27",
    "kind": "Animated Signature",
    "category": "motion",
    "description": "Animated signature banner.",
    "src": "assets/portfolio/59-motion-study-27.gif",
    "width": 400,
    "height": 160,
    "orientation": "banner",
    "animated": true,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "motion-study-28",
    "title": "Animated Signature 28",
    "kind": "Animated Signature",
    "category": "motion",
    "description": "Animated signature banner.",
    "src": "assets/portfolio/60-motion-study-28.gif",
    "width": 400,
    "height": 160,
    "orientation": "banner",
    "animated": true,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "web-designs-cover",
    "title": "Web Designs Cover",
    "kind": "Brand System",
    "category": "brand",
    "description": "Fluxframe web designs cover tile.",
    "src": "assets/portfolio/61-web-designs-cover.png",
    "width": 795,
    "height": 621,
    "orientation": "wide",
    "animated": false,
    "featured": true,
    "hero": true,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "motion-study-29",
    "title": "Animated Signature 29",
    "kind": "Animated Signature",
    "category": "motion",
    "description": "Animated signature banner.",
    "src": "assets/portfolio/62-motion-study-29.gif",
    "width": 400,
    "height": 160,
    "orientation": "banner",
    "animated": true,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "motion-study-30",
    "title": "Animated Signature 30",
    "kind": "Animated Signature",
    "category": "motion",
    "description": "Animated signature banner.",
    "src": "assets/portfolio/63-motion-study-30.gif",
    "width": 600,
    "height": 240,
    "orientation": "banner",
    "animated": true,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "motion-study-31",
    "title": "Animated Signature 31",
    "kind": "Animated Signature",
    "category": "motion",
    "description": "Animated signature banner.",
    "src": "assets/portfolio/64-motion-study-31.gif",
    "width": 400,
    "height": 160,
    "orientation": "banner",
    "animated": true,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "Portfolio"
  },
  {
    "id": "instagram-milestone-alt",
    "title": "Instagram Milestone Alt",
    "kind": "NFT Campaign",
    "category": "nft",
    "description": "Alternate square HypeBears milestone artwork.",
    "src": "assets/portfolio/65-instagram-milestone-alt.jpg",
    "width": 1280,
    "height": 1280,
    "orientation": "square",
    "animated": false,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "2022"
  },
  {
    "id": "hype-bears-hero",
    "title": "Hype Bears",
    "kind": "Startup Project / NFT Launch",
    "category": "crypto",
    "description": "Black-and-gold Hype Bears hero banner.",
    "src": "assets/portfolio/66-hype-bears-hero.jpeg",
    "width": 1500,
    "height": 500,
    "orientation": "banner",
    "animated": false,
    "featured": true,
    "hero": true,
    "webCase": false,
    "year": "2022"
  },
  {
    "id": "hype-bears-archive",
    "title": "PSSD",
    "kind": "Startup Project",
    "category": "crypto",
    "description": "PSSD dark project cover and startup visual system.",
    "src": "assets/portfolio/67-hype-bears-archive.png",
    "width": 795,
    "height": 621,
    "orientation": "wide",
    "animated": false,
    "featured": false,
    "hero": false,
    "webCase": false,
    "year": "2022"
  }
];
